"""empty message

Revision ID: 16333b8af9f2
Revises: 
Create Date: 2020-09-16 20:51:15.739025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16333b8af9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason_for_report', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('vehicle_colour', sa.String(), nullable=True),
    sa.Column('vehicle_brand', sa.String(), nullable=True),
    sa.Column('details_body', sa.String(), nullable=True),
    sa.Column('location_road_name', sa.String(), nullable=True),
    sa.Column('location_postcode', sa.String(), nullable=True),
    sa.Column('location_city_name', sa.String(), nullable=True),
    sa.Column('location_latitude', sa.Integer(), nullable=True),
    sa.Column('location_longitude', sa.Integer(), nullable=True),
    sa.Column('council_name', sa.String(), nullable=True),
    sa.Column('report_unique_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('image')
    # ### end Alembic commands ###
